filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer upgrade --no-interaction --prefer-dist
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
tools:
  external_code_coverage:
    timeout: 600 # default is 300 seconds